- src/components/søknad-details/SøknadDetails.module.css
- src/components/søknad-details/SøknadDetails.tsx
- src/components/søknad-summary-section/SøknadSummarySection.tsx
- src/types/Søknad.ts
Løser: https://trello.com/c/Jq3y593n/41-vise-antall-vedlegg-i-frontend
Fant ingen skisser på hvordan det skulle se ut, så tok til i det kreative hjørnet. Men får ta kontakt med Joachim til uka.
Selve raden i oppsummeringa vil kun vises hvis det er noen vedlegg i det hele tatt.
> Vis antall vedlegg knyttet til søknad

- src/components/header/Header.test.tsx
- src/components/header/Header.tsx
- src/pages/_app.tsx
Trimmer søkestrengen for å fjerne whitespaces
> Saniter søkefelt ved å fjerne whitespaces

- src/components/alder-vilkårsvurdering-table/AlderVilkårsvurderingTable.tsx
- src/components/bruker-fyller-18-år-i-perioden-melding/BrukerFyller18ÅrIPeriodenMelding.tsx
- src/components/bruker-under-18-år-i-hele-perioden-melding/BrukerUnder18ÅrIHelePeriodenMelding.tsx
- src/components/søknad-tabs/SøknadTabs.tsx
- src/components/vedtak-utfall-text/VedtakUtfallText.tsx
- src/components/vilkårsvurdering-details/VilkårsvurderingDetails.tsx
- src/pages/soker/[...all].tsx
- src/types/AlderVilkårsvurdering.ts
- src/types/Behandling.ts
- src/types/Personalia.ts
Under arbeid. Skal ikke merges før https://github.com/navikt/tiltakspenger-vedtak/pull/155 er merget. Kan komme flere justeringer her utifra PRen i tiltakspenger-vedtak.
> Visning av vilkårsvurdering av alder

- package-lock.json
- package.json
- src/components/error-fallback/error-fallback.tsx
- src/components/header/Header.test.tsx
- src/components/header/Header.tsx
- src/components/loaders/Loaders.tsx
- src/pages/_app.tsx
- src/pages/soker/[...all].tsx
- src/types/Søker.ts
- src/utils/http.ts
- refaktorer hoved page (_app)
- legg til småendringer i header
- legg til småendringer i header
> Refaktorer _app

- package-lock.json
- package.json
- src/components/oppdatert-data-tilgjenglig-melding/OppdatertDataTilgjengeligMelding.module.css
- src/components/oppdatert-data-tilgjenglig-melding/OppdatertDataTilgjengeligMelding.tsx
- src/components/søknad-tabs/SøknadTabs.tsx
- src/components/vilkårsvurdering-details/VilkårsvurderingDetails.tsx
- src/hooks/useRefreshPolling.ts
- src/pages/soker/[...all].tsx
- src/types/Behandling.ts
- src/types/Søker.ts
Lagde en hook som poller backend og sjekker om hash har endret seg. Hvis den har det invaliderer den cache som finnes på søknaden og den blir hentet inn på nytt.
> Refresh-mekanisme for å holde data oppdatert

- src/components/toaster/Toaster.tsx
- src/core/useSaksbehandler.ts
- src/core/useSokOppPerson.ts
- src/core/useSoknader.ts
- src/layouts/page/PageLayout.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/utils/http.ts
Introduserer tilbake feilmeldinger. Feilmeldinger via fetch vil nå dukke opp samme sted.
> Reintroduser feilemldinger

- src/pages/index.tsx
Hører sammen med denne : https://github.com/navikt/tiltakspenger-vedtak/pull/335
> F Legg til Type Behandling og Periode i benken

- src/containers/begrunnelse-modal/BegrunnelseModal.module.css
- src/containers/begrunnelse-modal/BegrunnelseModal.tsx
- src/containers/behandling-knapper/BehandlingKnapper.tsx
- src/pages/behandling/[...all].tsx
- src/pages/soker/[...all].tsx
Lagt til modal med mulighet for beslutter å velge begrunnelse
Implementert:
Figma:
> 495 begrunnelse fra beslutter

- .github/pull_request_template.md
Lager en PR-template slik som vi snakket om på utviklingsmøtet i forrige uke! Denne kan hjelpe oss med å huske på å få inn nyttig informasjon til de som skal se over PR-ene våre, og forhåpentligvis gjøre review-prosessen enklere! Jeg har slengt inn noen punkter jeg tror kan være nyttige, men gjerne kom med forslag til endringer! 😄 
Når denne godkjennes tenker jeg å legge templaten inn i de andre repoene våre også uten å lage PR på det så vi slipper 25+ pr-er! 😉
> Lag en pull request template

- src/pages/index.tsx
Knapp for å ta behandling ruter nå til behandlingen
> F - Knapp for å ta behandling ruter til behandlingen

- src/components/meldekort-beregning-visning/MeldekortBeregningsVisning.tsx
- src/components/meldekort-side/Meldekort.module.css
- src/components/meldekort-side/MeldekortSide.tsx
- src/components/meldekort-side/MeldekortUke.tsx
- src/components/meldekort-side/MeldekortUkeDag.tsx
- src/hooks/useHentMeldekort.ts
- src/hooks/useHentMeldekortBeregning.ts
- src/types/MeldekortTypes.ts
I denne PRen, viser vi løpende bergning, det betyr at når man endrer status i meldekortet da skal det endres antall dager i Beregning component
Denne PR inneholder også litt css endring til meldekortet
> 744 vise løpende beregning

- src/components/saksopplysning-tabell/RedigeringSkjema.tsx
- src/components/saksopplysning-tabell/Saksopplysning.tsx
- src/components/saksopplysning-tabell/SaksopplysningTabell.tsx
Sørger for at tekster i redigeringsskjema på vilkår gir mer mening iht vilkåret og saksopplysningen som endres på.
Sørger for at tekster i redigeringsskjema på vilkår gir mer mening iht vilkåret og saksopplysningen som endres på.
Nei. Diskutert om vi må gjøre ting mindre generelt her etterhvert, hvis det kommer behov for mye spesialtilpasninger på ulike vilkår osv.
Kun endringer i tekst
> R Endret tekster i Redigeringsskjema

- src/hooks/useSokOppPerson.ts
- src/pages/_app.tsx
- src/pages/sak/Sak.module.css
- src/pages/sak/[sakId].tsx
- src/pages/saker/[søkerId].tsx
- src/types/Behandling.ts
- src/utils/auth.ts
> 814 lage saksøkside

- src/components/saksopplysning-tabell/Saksopplysning.tsx
- src/components/saksopplysning-tabell/SaksopplysningTabell.tsx
- src/components/vilkårsvurdering/Vilkårsvurdering.tsx
- src/types/Behandling.ts
- tsconfig.json
Viser lenke til lovreferense under kategori og på hver vilkår slik at når man skal trykke på den lenken så skal det åpnes en ny fane med urlen til lovata
> F La lovreferense til kategori og vilkår

- src/components/flervalgsfelt/Flervalgsfelt.tsx
- src/components/saksopplysning-tabell/PeriodeVelger.tsx
- src/components/saksopplysning-tabell/Periodefelt.tsx
- src/components/saksopplysning-tabell/RedigeringSkjema.tsx
- src/components/tiltaksdeltagelse-demo/TiltakCard.tsx
- src/components/tiltaksdeltagelse-demo/TiltaksdeltagelseDemo.module.css
- src/components/tiltaksdeltagelse-demo/TiltaksdeltagelseDemo.tsx
- src/components/tiltaksdeltagelse-demo/TiltaksdeltagelseForm.tsx
- src/components/tiltaksdeltagelse-demo/TiltaksdeltagelseTable.tsx
- src/components/tiltaksdeltagelse-demo/types.ts
- src/pages/sandbox/index.tsx
- src/utils/validation.ts
> F Påbegynt vilkårsvurdering tiltaksdeltagelse

- src/components/flervalgsfelt/Flervalgsfelt.tsx
- src/components/registrert-tiltak-detaljer/RegistrertTiltakDetaljer.tsx
- src/components/vilkårsvurdering-av-stønadsdager/EndreAntallDagerModal.tsx
- src/components/vilkårsvurdering-av-stønadsdager/TiltakMedAntallDager.module.css
- src/components/vilkårsvurdering-av-stønadsdager/TiltakMedAntallDager.tsx
- src/components/vilkårsvurdering-av-stønadsdager/TiltaksdagerTabell.module.css
- src/components/vilkårsvurdering-av-stønadsdager/TiltaksdagerTabell.tsx
- src/components/vilkårsvurdering-av-stønadsdager/TiltaksdataFraRegister.module.css
- src/components/vilkårsvurdering-av-stønadsdager/TiltaksdataFraRegister.tsx
- src/components/vilkårsvurdering-av-stønadsdager/VilkårsvurderingAvStønadsdager.tsx
- src/components/vilkårsvurdering-av-stønadsdager/VilkårsvurderingAvStønadsdagerHeading.tsx
- src/pages/api/[...middleware].ts
- src/pages/behandling/[behandlingId]/ovrigevilkar/index.tsx
- src/types/Søknad.ts
Obs! Work in progress. Modalen er ikke lagd enda, men det kommer.
> F Lagd nytt design på tiltaksdager

- src/components/steg/Introduksjonsprogrammet.tsx
- src/hooks/useHentIntroduksjonsprogrammet.ts
- src/types/Introduksjonsprogrammet.ts
- src/types/Kvp.ts
Kopierte koden for KVP og byttet ut 'KVP' med 'Introduksjonsprogrammet'
> F Legg til kobling mot nytt Introduksjonsprogrammet-endepunkt i backend

- src/components/vilkår/Alder.tsx
- src/hooks/vilkår/useHentAlder.ts
- src/types/AlderTypes.ts
Har gitt samme treatment til 'alderVilkåret' som de andre vilkårene!
Ser relativt likt ut, men med data hentet ut fra nytt endepunkt.
> F Alder-siden skal hente data fra nytt endepunkt i backend.

- src/components/behandling/førstegangsbehandling/6-avbryt-behandling/FørstegangsvedtakAvbrytBehandling.module.css
- src/components/behandling/førstegangsbehandling/6-avbryt-behandling/FørstegangsvedtakAvbrytBehandling.tsx
- src/components/behandling/førstegangsbehandling/FørstegangsVedtak.tsx
- src/components/behandlingsknapper/BehandlingKnappForOversikt.tsx
- src/components/behandlingsknapper/BehandlingKnapper.module.css
- src/components/behandlingsknapper/start-behandling/StartSøknadBehandling.tsx
- src/components/benk/BenkSide.tsx
- src/components/saksoversikt/avsluttBehandling/AvsluttBehandling.module.css
- src/components/saksoversikt/avsluttBehandling/AvsluttBehandling.tsx
- src/components/saksoversikt/behandlinger-oversikt/BehandlingerOversikt.tsx
- src/context/sak/SakContext.ts
- src/context/sak/SakProvider.tsx
- src/types/SøknadTypes.ts
- src/types/common.ts
Knapper for å avslutte en søknad / behandling
Ingen kommentarer
Se figma: https://www.figma.com/design/f2LE8xWawucbdQN5ed5JpJ/Tiltakspenger-sak?node-id=1340-2777&p=f&m=dev
> Avslutt behandling

- src/components/behandling/saksopplysninger/tiltak/BehandlingTiltakOpplysninger.tsx
La merke til at vi viste samme tiltaksdeltakelsen to ganger.
> unngå å vise samme tiltak to ganger

- src/components/meldekort/meldekortdetaljer/MeldekortDetaljer.module.css
- src/components/meldekort/meldekortdetaljer/MeldekortDetaljer.tsx
- src/types/meldekort/Meldeperiode.ts
Må støtte at tiltakstypen kan være en liste
https://trello.com/c/W9ifbenn/1315-st%C3%B8tte-at-vi-f%C3%A5r-flere-tiltak-fra-arena-komet-n%C3%A5r-vi-s%C3%B8ker-opp-et-fnr
> støtter at tiltakstypen kan være en liste

- src/components/behandling/førstegangsbehandling/3-tiltak/perioder/TiltakPerioder.tsx
- src/components/behandling/førstegangsbehandling/førstegangsVedtakValidering.ts
- src/utils/behandling.ts
- Skal ikke kunne fjerne tiltaksperiode hvis det kun fantes en periode
- Kan bare velge tiltak som har datoer
- Kan bare velge et gitt tiltak for periode der brukeren deltar på tiltaket
- Kan ikke innvilge tiltakspenger for en periode der personen ikke deltar på tiltak
https://trello.com/c/iwTGibtq/1376-saksbehandler-skal-ikke-kunne-innvilge-tiltakspenger-for-dager-man-ikke-deltar-p%C3%A5-tiltak
> Validering

- .github/workflows/.test-and-build.yml
- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/test-and-build-on-push.yml
- .nais/nais.yml
- src/components/modaler/BekreftelsesModal.tsx
Fjerner det at det står "Feil: <feilkode>" foranfeilmeldingen i modalen etter ønske fra Sølvi. 
Legger også til loki-logging og fjerner noen properties som gha klager på. 
https://trello.com/c/6MmwaO9M/1434-bedre-feilmeldinger-n%C3%A5r-en-saksbehandler-gj%C3%B8r-en-handling-p%C3%A5-en-behandling-som-ikke-er-sin-egen
> Feilmelding errorcode

- src/components/behandlingsknapper/BehandlingKnappForOversikt.tsx
- src/components/saksoversikt/meldekort-oversikt/MeldekortBehandlingKnappForOversikt.tsx
- src/utils/tilganger.ts
Ref feil oppdaget under testing av https://trello.com/c/iYXkiirR/1458-en-p%C3%A5startet-manuell-meldekortbehandling-m%C3%A5-kunne-overtas-av-en-annen-saksbehandler
> skal ikke få overta behandling som beslutter uten beslutterrolle

- src/components/behandling/førstegangsbehandling/3-dager-per-meldeperiode/FørstegangsVedtakDagerPerMeldeperiode.module.css
https://trello.com/c/UETq0Y9i/1342-la-saksbehandler-legge-inn-antall-dager-per-meldeperiode-uten-mulighet-for-periodisering
> 1342 justerer ned størrelsen for dager pr meldeperiode

- src/components/meldekort/2-hovedseksjon/behandling/utfylling/MeldekortUtfylling.tsx
- src/components/saksoversikt/meldekort-oversikt/avsluttMeldekortBehandling/AvsluttMeldekortBehandling.tsx
Dropper å bruke form så vi kan avslutte også inne på meldekortbehandlingen. 
https://trello.com/c/XU9ti14p/1461-mulig-for-saksbehandler-%C3%A5-avslutte-manuell-meldekortbehandling
> Avslutt meldekortbehandling knapp

- src/components/behandling/saksopplysninger/søknad/SøknadOpplysningerPengestøtter.tsx
- src/components/oppsummeringer/oppsummeringAvSøknad/OppsummeringAvSøknad.module.css
- src/components/oppsummeringer/oppsummeringAvSøknad/OppsummeringAvSøknad.tsx
https://trello.com/c/tho8NxRQ/1425-tydligere-markering-dersom-bruker-har-svart-ja-p%C3%A5-sp%C3%B8rsm%C3%A5lene-i-s%C3%B8knaden
> 1425 markerer hvis bruker har svart ja i søknad

- src/components/saksoversikt/behandlinger-oversikt/AvbrutteBehandlingerTabell.tsx
- src/components/saksoversikt/behandlinger-oversikt/AvsluttedeBehandlinger.tsx
- src/components/saksoversikt/behandlinger-oversikt/AvsluttedeBehandlingerUtils.ts
- src/components/saksoversikt/behandlinger-oversikt/VedtatteBehandlingerTabell.tsx
Flytter diverse tabeller inn i egne komponenter for bedre oversikt.
> 1484 Vis saksbehandler og beslutter på vedtatte og avbrutte behandlinger

- src/components/behandling/revurdering/innvilgelse/7-send-og-godkjenn/RevurderingInnvilgelseSend.tsx
- src/components/behandling/revurdering/stans/4-send/RevurderingStansSend.tsx
- src/components/behandling/revurdering/useSendRevurderingVedtak.ts
- src/components/behandling/søknadsbehandling/9-send-og-godkjenn/useSendSøknadsbehandling.ts
- src/types/VedtakTyper.ts
Oppdateringer for type-endringer fra https://github.com/navikt/tiltakspenger-saksbehandling-api/pull/1094/
> Oppdaterer DTO typer for send inn behandling-vedtak

- src/components/benk/BenkSide.tsx
- src/types/Behandlingssammendrag.ts
https://trello.com/c/D1dGCGcv/1552-saksbehandler-og-beslutter-skal-kunne-sette-en-behandling-p%C3%A5-vent
> 1552 La saksbehandler filtrere på hvorvidt behandlinger er satt på vent eller ei

- src/components/benk/BenkSide.tsx
- src/components/benk/BenkSideUtils.ts
- src/components/tabell/SortableTable.tsx
- src/types/Behandlingssammendrag.ts
https://trello.com/c/D1dGCGcv/1552-saksbehandler-og-beslutter-skal-kunne-sette-en-behandling-p%C3%A5-vent
> 1552 La saksbehandler filtrere benken på når behandlingen ble sist endret

- src/components/behandling/felles/barnetillegg/BehandlingBarnetillegg.tsx
- src/components/behandling/revurdering/innvilgelse/5-barn/RevurderingInnvilgelseBarnetillegg.tsx
- src/components/behandling/søknadsbehandling/7-barn/SøknadsbehandlingBarnetillegg.tsx
https://trello.com/c/YZyEGMLF/1480-endre-ordlyden-i-sp%C3%B8rsm%C3%A5l-om-barnetillegg-i-s%C3%B8knadsbehandling-legge-inn-infoboks
> 1480 endrer spm-tekst for barnetillegg og legger til infoboks

- src/components/behandling/felles/validering/validerAntallDagerPerMeldeperiode.ts
- src/components/behandling/felles/validering/validerInnvilgelse.ts
https://trello.com/c/kTaYKnjX/1568-bug-forbedring-av-feilmelding-ved-validering-av-datoer
> 1568 validerer antall dager pr meldeperiode opp mot innvilgelsesperiode

- src/components/saksoversikt/Saksoversikt.tsx
- src/components/saksoversikt/behandlinger-oversikt/BehandlingerOversikt.tsx
- src/components/saksoversikt/meldekort-oversikt/MeldekortOversikt.tsx
Har også forsøkt å gjøre visningene litt mer like, f.eks. er "ukjent" byttet ut med "-" og menyvalgene vises mer likt. 
https://trello.com/c/j1meD0me/1638-flytte-meldekort-oppgaver-som-krever-behandling-under-behandlinger-p%C3%A5-personoversikt
> Vise meldekort som krever saksbehandlers oppmerksomhet i listen over behandlinger
